version: "3.0"
services:
  e2e:
    container_name: rp-framework
    build: .
    environment:
       - SELENIUM_ADDRESS=http://selenium:4444/wd/hub
    volumes:
      - ./reports:/workdir/reports
    tty: true
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
