version: "3.0"
services:
  e2e:
    container_name: rp-framework
    build: .
    environment:
       - SELENIUM_ADDRESS=http://host.docker.internal:4444/wd/hub
    volumes:
      - ./reports:/workdir/reports
    tty: true
